#!/bin/bash
#
verbose=0

find . -maxdepth 1 -type f | xargs -I {} sh -c 'yadm ls-files --error-unmatch "{}" > /dev/null 2>&1 && echo "\e[1;32m[Tracked]\e[0m  {}" || echo "\e[1;31m[Untracked]\e[0m  {}"'

